# Generated by Django 4.2.5 on 2024-05-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0004_qc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push_to_pm_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('my_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.my_upload_file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.pm')),
            ],
        ),
    ]
