# Generated by Django 4.2.5 on 2024-05-22 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Json', '0007_remove_push_to_pm_file_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_Qc_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_file', models.FileField(upload_to='qc')),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('my_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.my_upload_file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
