# Generated by Django 4.2.5 on 2024-05-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0008_my_qc_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='push_to_pm_file',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
