# Generated by Django 4.2.5 on 2024-05-22 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0009_push_to_pm_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_qc_data',
            name='my_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.push_to_pm_file'),
        ),
        migrations.AlterField(
            model_name='my_qc_data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.qc_user'),
        ),
    ]
