# Generated by Django 4.2.5 on 2024-05-22 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Json', '0010_alter_my_qc_data_my_file_alter_my_qc_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_qc_data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
