# Generated by Django 4.2.5 on 2024-05-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0011_alter_my_qc_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_qc_data',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
