# Generated by Django 4.2.5 on 2024-05-26 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0013_ed_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor_push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta', models.BooleanField(default=False)),
                ('Ed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.ed_user')),
                ('qc_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.my_qc_data')),
                ('qc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.qc_user')),
            ],
        ),
    ]
