# Generated by Django 4.2.5 on 2024-05-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0014_editor_push'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('st', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.my_upload_file')),
            ],
        ),
    ]
