# Generated by Django 4.2.5 on 2024-05-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0015_add_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_col',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.push_to_pm_file'),
        ),
    ]
