# Generated by Django 4.2.5 on 2024-05-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0017_add_col_qc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_col_qc',
            name='eid',
        ),
    ]
