# Generated by Django 4.2.5 on 2024-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0018_remove_add_col_qc_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_col_qc',
            name='col',
            field=models.CharField(default='', max_length=100),
        ),
    ]
