# Generated by Django 4.2.5 on 2024-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0019_add_col_qc_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_col_qc',
            name='data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
