# Generated by Django 4.2.5 on 2024-05-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0020_add_col_qc_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_data_PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('Edited_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.editor_push')),
                ('editior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.ed_user')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Json.pm')),
            ],
        ),
    ]
