# Generated by Django 4.2.5 on 2024-05-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0021_final_data_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='final_data_pm',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
