# Generated by Django 4.2.5 on 2024-05-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Json', '0022_file_name_alter_final_data_pm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_qc_data',
            name='msg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
